"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env', override=False)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-ajbib*idp38&$xxrm==cug&un+^i-5bn+ltke4q5gxa2$)0#jr',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# True when running `manage.py test`. Used to send contact-form emails
# synchronously in tests, so `mail.outbox` assertions stay deterministic,
# while real requests send them in a background thread (see contact/emails.py).
TESTING = 'test' in sys.argv

# Must be set in production, otherwise Django starts returning 400.
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # third party
    'rest_framework',
    'corsheaders',

    # local
    'contact',
    'calculator',
    'solar_panels',
    'inverters',
    'batteries',
    'products',
    'quotes',
    'orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # CorsMiddleware must come BEFORE CommonMiddleware, otherwise the
    # preflight (OPTIONS) request fails.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.parse(os.environ['DATABASE_URL'], conn_max_age=600),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Uploaded electricity bills (calculator app).
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/hour',
        'contact': '5/hour',  # 5 messages per hour per IP is plenty
        'calculator': '5/hour',  # same reasoning as contact
        'quote': '5/hour',  # same reasoning as contact
        'order': '5/hour',  # same reasoning as contact
    },
}


# CORS
# https://github.com/adamchainz/django-cors-headers

CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        'http://localhost:3000,http://127.0.0.1:3000',
    ).split(',')
    if o.strip()
]

# Origins allowed to POST cross-site (e.g. Django admin login) over HTTPS.
# Needed because Railway terminates TLS in front of the app.
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if o.strip()
]

# Railway sits behind a proxy that terminates TLS; trust its forwarded header
# so Django knows the original request was HTTPS (needed for CSRF/cookies).
if os.environ.get('RAILWAY_ENVIRONMENT'):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# MAILERS is the current API in Django 6.1 (the old EMAIL_* settings are
# removed in 7.0). With no EMAIL_HOST configured, mail is printed to the
# terminal so local development needs no SMTP setup at all. Setting EMAIL_HOST
# (see `.env`) switches to real SMTP delivery.

if os.environ.get('EMAIL_HOST'):
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
            'OPTIONS': {
                'host': os.environ['EMAIL_HOST'],
                'port': int(os.environ.get('EMAIL_PORT', 587)),
                'username': os.environ.get('EMAIL_HOST_USER', ''),
                'password': os.environ.get('EMAIL_HOST_PASSWORD', ''),
                'use_tls': os.environ.get('EMAIL_USE_TLS', 'True') == 'True',
                'timeout': 10,
            },
        },
    }
else:
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.console.EmailBackend',
        },
    }

DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL', 'Madni Solar <zain.saleem155@gmail.com>'
)

# Addresses that receive a notification when a new contact message arrives.
CONTACT_NOTIFY_EMAILS = [
    e.strip()
    for e in os.environ.get('CONTACT_NOTIFY_EMAILS', 'zain.saleem155@gmail.com').split(',')
    if e.strip()
]

# Addresses that receive a notification when a new calculator submission arrives.
CALCULATOR_NOTIFY_EMAILS = [
    e.strip()
    for e in os.environ.get('CALCULATOR_NOTIFY_EMAILS', 'zain.saleem155@gmail.com').split(',')
    if e.strip()
]

# Addresses that receive a notification when a new quote request arrives.
QUOTE_NOTIFY_EMAILS = [
    e.strip()
    for e in os.environ.get('QUOTE_NOTIFY_EMAILS', 'zain.saleem155@gmail.com').split(',')
    if e.strip()
]

# Addresses that receive a notification when a new order arrives.
ORDER_NOTIFY_EMAILS = [
    e.strip()
    for e in os.environ.get('ORDER_NOTIFY_EMAILS', 'zain.saleem155@gmail.com').split(',')
    if e.strip()
]

# Flat delivery charge applied to every order. Lives here rather than in the
# checkout UI so the number has one home - the frontend reads it from
# GET /api/orders/settings/ and the serializer recomputes every total with it.
ORDER_FLAT_SHIPPING = int(os.environ.get('ORDER_FLAT_SHIPPING', '2000'))

# Display currency for the checkout. Prices are stored as plain decimals, so
# this is a label, not a conversion.
ORDER_CURRENCY = os.environ.get('ORDER_CURRENCY', 'PKR')

# Used to build the admin link inside the notification email.
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')
