# Generated by Django 6.1.1 on 2026-09-14 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='batteries/brands/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_variants', to='batteries.brand')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text="Leave blank to auto-fill as 'battery-<brand slug>'.", max_length=220, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='batteries/products/')),
                ('short_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True, help_text='Paste the paragraph(s) as plain text. Separate multiple paragraphs with a blank line.')),
                ('why_choose', models.TextField(blank=True, help_text='One short checklist item per line.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='batteries.brand')),
            ],
            options={
                'ordering': ['brand__name', 'name'],
            },
        ),
    ]
