# Generated by Django 6.1.1 on 2026-09-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_type', models.CharField(choices=[('single', 'Single Phase'), ('three', 'Three Phase')], max_length=10)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_units', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_file', models.FileField(blank=True, null=True, upload_to='calculator/bills/%Y/%m/')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('house_area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('address', models.TextField()),
                ('loads', models.JSONField(default=dict)),
                ('load_calculated', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='calculator__created_50b5f0_idx')],
            },
        ),
    ]
