# Generated by Django 6.1.1 on 2026-09-18 10:15
#
# Only the field's `storage` changed - where the file is kept, which is not
# part of the column (still varchar(100)). The AlterField is therefore wrapped
# in SeparateDatabaseAndState so Django records the new field state without
# emitting a single statement against the database.

import backend.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='calculatorsubmission',
                    name='bill_file',
                    field=models.FileField(
                        blank=True,
                        null=True,
                        storage=backend.storages.private_media_storage,
                        upload_to='calculator/bills/%Y/%m/',
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
