# Generated by Django 6.1.1 on 2026-09-20 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverters', '0005_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Leave blank unless the brand sits under more than one category - then pick which one this product belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inverters.category'),
        ),
    ]
