# Generated by Django 6.1.1 on 2026-09-22 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverters', '0007_backfill_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Sub-variants only. Leave blank unless the parent brand sits under more than one category - then pick which one this sub-variant belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='inverters.category'),
        ),
    ]
