# Generated by Django 6.1.1 on 2026-09-10 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='solar_panels/brands/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='solar_panels/products/')),
                ('short_description', models.TextField(blank=True)),
                ('description', models.JSONField(blank=True, default=list, help_text='List of paragraph strings, e.g. ["Para one.", "Para two."]')),
                ('why_choose', models.JSONField(blank=True, default=list, help_text='List of short strings, e.g. ["High efficiency", "Long lifespan"]')),
                ('categories', models.JSONField(blank=True, default=list, help_text='List of strings, e.g. ["Madni Solar", "Solar Panels", "Yingli"]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='solar_panels.brand')),
            ],
            options={
                'ordering': ['brand__name', 'name'],
            },
        ),
    ]
