# Generated by Django 6.1.1 on 2026-09-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_panels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Paste the paragraph(s) as plain text. Separate multiple paragraphs with a blank line.'),
        ),
    ]
