# Generated by Django 6.1.1 on 2026-09-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar_panels', '0003_fix_json_string_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='product',
            name='why_choose',
        ),
    ]
